FROM hanyuu/rbpf-rust-builder:x86_64 AS builder

WORKDIR /app

COPY ./rbpf-common/ ./rbpf-common/
COPY ./rbpf-ebpf/ ./rbpf-ebpf/
COPY ./rbpf-http/ ./rbpf-http/
COPY ./rbpf-loader/ ./rbpf-loader/
COPY ./contrib/ ./contrib/

RUN cargo build --release --features embed-ebpf --target-dir=/app/target/
