FROM archlinux:base-devel

RUN pacman -Sy --noconfirm git sudo \
  && useradd -m builder && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers \
  && mkdir -p /home/builder/pkgbuild && chown builder:builder /home/builder/pkgbuild

WORKDIR /home/builder/pkgbuild
USER builder

CMD ["/bin/bash"]
