# Dockerfile.rpmbuild
FROM fedora:latest

RUN dnf install -y rpm-build rpmdevtools sudo && \
    useradd -m builder && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    mkdir -p /home/builder/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS} && \
    chown -R builder:builder /home/builder

USER builder
WORKDIR /home/builder/rpmbuild

# Копируем только нужное
COPY rbpf-build /home/builder/rbpf-build
COPY contrib/pkg /home/builder/pkg

CMD ["bash"]
