[package]
name = "rbpf-common"
version = "0.1.1"
edition = "2021"

[features]
default = []
user = ["aya", "serde"]

[dependencies]
aya = { workspace = true, optional = true }
serde = { version = "1.0.219", optional = true }


[lib]
path = "src/lib.rs"
