[package]
name = "rbpf-ebpf"
version = "0.2.0"
edition = "2024"
license = "MIT"

[dependencies]
aya-ebpf = { workspace = true }
network-types = "0.0.7"

rbpf-common = { path = "../rbpf-common" }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "rbpf"
path = "src/main.rs"
