version: "3.7"
services:
  elasticsearch:
    image: elasticsearch:8.18.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elk
#  logstash:
#    image: logstash:8.12.1
#    container_name: logstash
#    ports:
#      - "5044:5044"
#      - "9600:9600"
#    volumes:
#      - ./logstash/pipeline:/usr/share/logstash/pipeline
#      - ./logstash/config:/usr/share/logstash/config
#    environment:
#      - LS_JAVA_OPTS=-Xms256m -Xmx256m
#    depends_on:
#      - elasticsearch
#    networks:
#      - elk
  kibana:
    image: kibana:8.12.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    depends_on:
      - elasticsearch
    networks:
      - elk
volumes:
  esdata:
networks:
  elk: